### ISSUE TITLE
Is it possible to add multiple faults at once? 

### ISSUE THREAD

**Issue by Tiago-Ferreira-Git** [sandialabs/snl-pstess#1]
Hello,

I am trying to use this toolbox to compare to my Load Frequency control results and I would like to implement multiple line faults at once. Does PSTESS allow this?

**Comment by rthoma** [comment]
Hi there, thanks for reaching out. I’d like to understand what you’re trying to do a bit better. Would you like to trip multiple lines in response to a disturbance, or actually implement simultaneous faults at different points in the system? We have a mechanism for the former, but the latter is not something that we’ve considered. If you provide a bit more info, maybe a description of an example scenario, I’ll see if we can get you pointed in the right direction.

**Comment by Tiago-Ferreira-Git** [comment]
Hello! Yes, I would like to trip simultaneous lines at different points at once.  I just wanted to check If it was implemented, since it is not maybe I will remove my question, as it is not the most important feature to implement I believe.

Best regards!

**Comment by rthoma** [comment]
Hi Tiago, please see the trip_logic.m function. By setting line_trip_out to true at the appropriate point in your simulation (for the lines of interest), you can trip whichever lines you want. If you trip too many, you may run into trouble with power flow convergence, so keep that in mind. Also be sure to align the timing with your contingency specified in sw_con. For example, maybe your fault occurs at t=1s and is cleared a few cycles later. In that case, you’d want to set line_trip_out to true for the tripped lines at the same time (or shortly after) as the fault is cleared. Take a look, and feel free to follow up with any additional questions.

**Comment by Tiago-Ferreira-Git** [comment]
Hello! Yes, I would like to trip simultaneous lines at different points at once.  I just wanted to check If it was implemented, since it is not maybe I will remove my question from github.

Best regards!
________________________________
De: rthoma ***@***.***>
Enviado: 25 de julho de 2024 17:25
Para: sandialabs/snl-pstess ***@***.***>
Cc: Tiago ***@***.***>; Author ***@***.***>
Assunto: Re: [sandialabs/snl-pstess] Is it possible to add multiple faults at once? (Issue #1)


Hi there, thanks for reaching out. I’d like to understand what you’re trying to do a bit better. Would you like to trip multiple lines in response to a disturbance, or actually implement simultaneous faults at different points in the system? We have a mechanism for the former, but the latter is not something that we’ve considered. If you provide a bit more info, maybe a description of an example scenario, I’ll see if we can get you pointed in the right direction.

**Comment by rthoma** [comment]
Thanks, what I’m trying to communicate is that you can do it, you just have to use trip_logic.m instead of specifying the trips in sw_con. Best of luck with your research~

**Comment by Tiago-Ferreira-Git** [comment]
Good morning,

Sorry to keep bothering you about this, but how would one use the trip_logic.m? There is no mention to trip_logic in the documentation. I see that in example d2asbegp_ess.m Generator 3 is tripped. However, when I run this example, the run never reaches trip_logic. Moreover, I see that in this file there is a comment at the sw_con variable that says to use the type 4 to trip the generator, is this correct?

**Comment by rthoma** [comment]
Hi Tiago,

This is a new feature that we're currently developing. We're working on documentation and examples now. You can think of `trip_logic.m` as a mechanism for implementing protection schemes (and SPS). But it can also be used to implement complex contingencies, like the loss of multiple lines. The header of `trip_logic.m` has useful information. Here's a simple example of code that you might include (at line 66):
```
if (t(k) > 1)
    line_trip_out([1,2]) = true; 
end
```
This would trip the first and second branches (elements of `line`) after the 1-second mark in the simulation. The basic idea is that `sw_con` and `trip_logic.m` are independent. You can simulate a contingency via `sw_con` as you normally would, and then handle the second stage of the event (or relevant protection schemes) using `trip_logic.m`. Since this feature is new, make sure to evaluate the results of all simulations to ensure it behaves as you expect.

As for your other question, yes, setting the type field of `sw_con` to 4 is the standard way to implement loss of generation events.
